server {
    listen 80;
    server_name _;

    # Раздача статики
    location /spisok-del-todo-app/ {
        alias /usr/share/nginx/html/spisok-del-todo-app/;
        index index.html;
        try_files $uri $uri/ /spisok-del-todo-app/index.html;
    }

    # Редирект без слеша на со слешем
    location = /spisok-del-todo-app {
        return 301 /spisok-del-todo-app/;
    }

    # Проксирование API запросов к backend
    location /todo-api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}